version: '3'
services:
  service-registry:
    image: 'devindia01/service-registry:0.0.1'
    container_name: 'service-registry'
    ports:
      - '8761:8761'
  config-server:
    image: 'devindia01/config-server:0.0.1'
    container_name: 'config-server'
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD","curl","-f","http://config-server:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - service-registry
  cloud-gateway:
    image: 'devindia01/cloud-gateway:latest'
    container_name: 'cloud-gateway'
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-registry:8761/eureka
      - CONFIG_SERVER_URL=config-server
    depends_on:
      config-server:
        condition: service_healthy